{{- if .Values.nodeAudienceRbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harbor-credential-provider.nodeAudienceRoleName" . }}
  labels:
    {{- include "harbor-credential-provider.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - {{ required "registry.host is required" (include "harbor-credential-provider.audience" .) | quote }}
    verbs:
      - request-serviceaccounts-token-audience
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harbor-credential-provider.nodeAudienceRoleName" . }}
  labels:
    {{- include "harbor-credential-provider.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harbor-credential-provider.nodeAudienceRoleName" . }}
subjects:
  {{- range .Values.nodeAudienceRbac.groups }}
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: {{ . | quote }}
  {{- end }}
{{- end }}
