apiVersion: v2
name: credential-provider-harbor
description: Deploy the credential-provider-harbor binary to Kubernetes nodes for Harbor Federated Robot Accounts
type: application
version: 0.1.1
appVersion: "0.0.1"
keywords:
  - harbor
  - credential-provider
  - federated-robot-accounts
  - fedidp
  - kubernetes
  - kubelet
maintainers:
  - name: container-registry
home: https://github.com/container-registry/harbor-workload-identity-federation
sources:
  - https://github.com/container-registry/harbor-workload-identity-federation
