kind: CredentialProviderConfig
apiVersion: kubelet.config.k8s.io/v1
providers:
  - name: credential-provider-harbor
    apiVersion: credentialprovider.kubelet.k8s.io/v1
    tokenAttributes:
      requireServiceAccount: true
      serviceAccountTokenAudience: "harbor.example.com"
      cacheType: Token
    matchImages:
      - "harbor.example.com"
    defaultCacheDuration: "1h"
    args:
      - "--username=jwt"
