apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: default
spec:
  serviceAccountName: default
  containers:
  - name: httpd
    # change this to an image you actually have in Harbor
    image: harbor.example.com/library/httpd
    imagePullPolicy: Always
